clone_depth: 1

for:
  -
    image: Visual Studio 2019
    
    environment:
        MSYSTEM: MINGW64
    
    install:
      - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'
      - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'
      - C:\msys64\usr\bin\bash.exe -lc 'pacman -S --noconfirm mingw-w64-x86_64-toolchain make'
    
    before_build:
      - git submodule update --init --recursive
      - git submodule foreach git pull origin master
      - ps: |
            $env:MSYS2_PATH=C:\msys64\usr\bin\bash.exe -c 'echo $PATH'
            $env:MSYS2_WD=C:\msys64\usr\bin\bash.exe -c 'pwd'
            $env:PREFIX=$env:MSYS2_WD
            $env:MATRIX=C:\msys64\usr\bin\bash.exe -c 'echo msvc:{x64,Win32}:{Debug,Release}'
            $env:TARGET=""
    
    build_script:
      - ps: |
            C:\msys64\usr\bin\bash.exe -lc '\
            PATH=\"$MSYS2_PATH:$PATH\" \
            mingw32-make -f $MSYS2_WD/RegionsMT/Makefile -j all\(gsl\)'
            
    test_script:
      - ps: |
            C:\msys64\usr\bin\bash.exe -lc '\
            PATH=\"$MSYS2_PATH:$PATH\" \
            mingw32-make -f $MSYS2_WD/RegionsMT/Makefile -j -k test\(gsl\) || true'
