clone_depth: 1

image: Visual Studio 2019

environment:
    matrix:
      - MSYSTEM: MSYS2
      - MSYSTEM: MINGW32
      - MSYSTEM: MINGW64

before_build:
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master
  - ps: |
        $env:TARGET=""
        $env:PREFIX="."
        $env:CHERE_INVOKING="1"
        $env:MSYS2_ARG_CONV_EXCL="*"

for:
  -
    matrix:
        only:
          - MSYSTEM: MSYS2

    install:
    # - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'
    # - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'
    # - C:\msys64\usr\bin\bash.exe -lc 'pacman -S --noconfirm --needed make'
    
    build_script:
      - ps: |
            $env:GIT=C:\msys64\usr\bin\bash.exe -c '/usr/bin/which git'
            $env:CMAKE=C:\msys64\usr\bin\bash.exe -c '/usr/bin/which cmake'
            $env:MATRIX=C:\msys64\usr\bin\bash.exe -c 'echo msvc:{x64,Win32}:{Debug,Release}'
            C:\msys64\usr\bin\bash.exe -lc 'make -f RegionsMT/Makefile -j all\(gsl\)'
            
    test_script:
      - ps: C:\msys64\usr\bin\bash.exe -lc 'make -f RegionsMT/Makefile -j -k test\(gsl\) || true'
            
    after_test:
      - ps: C:\msys64\usr\bin\bash.exe -lc 'make -f RegionsMT/Makefile -j CLEAN=git\(gsl\)\ all\(gsl\) clean'
      
  - 
    matrix:
        only:
          - MSYSTEM: MINGW32
          
    build_script:
        echo $MSYSTEM

  - 
    matrix:
        only:
          - MSYSTEM: MINGW64
          
    build_script:
        echo $MSYSTEM
