clone_depth: 1

for:
  -
    image: Visual Studio 2019
    
    environment:
        MSYSTEM: MINGW64
        MSYS2_ARG_CONV_EXCL: \*
      
    before_build:
      - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'
      - C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'    
    
    build_script:
      - C:\msys64\usr\bin\bash.exe -lc 'echo $MSYSTEM'
